# Generated by Django 2.2 on 2019-04-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190410_1548'),
        ('posts', '0004_remove_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='account.Profile'),
        ),
    ]
