# Generated by Django 2.2 on 2019-04-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_user_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='profile',
        ),
    ]
