# Generated by Django 2.2 on 2019-04-16 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_auto_20190416_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='account.Profile'),
        ),
    ]
